# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Done'), (3, 'Canceled'), (4, 'Postponed'), (5, 'Live')], default=1),
        ),
    ]
